version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "9000:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - "5435:5432"
