version: '3.8'

services:
  fastapi-app:
    build: .
    ports:
      - "9000:8080"
    restart: always
    command: ["python3", "main.py"]
    volumes:
      - .:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logs_db
    ports:
      - "5435:5432"
